# Generated by Django 4.2.7 on 2024-01-12 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaluo_id', models.IntegerField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('comentario', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estado_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('clave', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('estatusid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'estatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('honorario_id', models.AutoField(primary_key=True, serialize=False)),
                ('avaluo_id', models.IntegerField(blank=True)),
                ('razon', models.CharField(blank=True, max_length=250)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'honorarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('tipoid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('consecutivo', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tiposimb',
            fields=[
                ('tipoimbid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tiposimb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Valuadores',
            fields=[
                ('valuadorid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('appaterno', models.CharField(max_length=250)),
                ('apmaterno', models.CharField(max_length=250)),
                ('display', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'valuadores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('municipio_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estados')),
            ],
            options={
                'db_table': 'municipios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colonias',
            fields=[
                ('colonia_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.IntegerField()),
                ('homoclave', models.IntegerField()),
                ('nombre', models.CharField(max_length=250)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.municipios')),
            ],
            options={
                'db_table': 'colonias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avaluos',
            fields=[
                ('avaluoid', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('numeroint', models.IntegerField(blank=True, null=True)),
                ('entrecalle1', models.CharField(blank=True, max_length=200)),
                ('entrecalle2', models.CharField(blank=True, max_length=200)),
                ('edad', models.IntegerField(blank=True)),
                ('dtcreate', models.DateField(blank=True)),
                ('dtsolicitud', models.DateField(blank=True)),
                ('dtvaluador', models.DateField(blank=True)),
                ('dtcliente', models.DateField(blank=True)),
                ('dtcobro', models.DateField(blank=True)),
                ('dtpago', models.DateField(blank=True)),
                ('manzana', models.CharField(blank=True, max_length=50)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('consecutivo', models.IntegerField(blank=True)),
                ('m2t', models.FloatField(blank=True)),
                ('m2c', models.FloatField(blank=True)),
                ('valor', models.FloatField(blank=True)),
                ('nofactura', models.CharField(blank=True, max_length=50)),
                ('monto', models.FloatField(blank=True)),
                ('nofolio', models.ImageField(blank=True, max_length=50, upload_to='')),
                ('dictamen', models.CharField(blank=True, max_length=100)),
                ('proyecto', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientes')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colonias')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estatus')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipos')),
                ('tipoimb', models.ForeignKey(blank=True, default='80', on_delete=django.db.models.deletion.CASCADE, to='myapp.tiposimb')),
                ('valuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.valuadores')),
            ],
            options={
                'db_table': 'avaluos',
                'managed': True,
            },
        ),
    ]
