# Generated by Django 4.2.7 on 2024-01-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluos',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numeroint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
