# Generated by Django 4.2.7 on 2023-12-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='honorarios',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='tipoimb',
            field=models.ForeignKey(blank=True, default='80', on_delete=django.db.models.deletion.CASCADE, to='myapp.tiposimb'),
        ),
        migrations.AlterField(
            model_name='colonias',
            name='colonia_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
