# Generated by Django 4.2.7 on 2024-01-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='honorarios',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='avaluos',
            old_name='numero_dictamen',
            new_name='dictamen',
        ),
        migrations.RenameField(
            model_name='avaluos',
            old_name='nombre_proyecto',
            new_name='proyecto',
        ),
        migrations.AddField(
            model_name='avaluos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numeroint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='tipoimb',
            field=models.ForeignKey(blank=True, default='80', on_delete=django.db.models.deletion.CASCADE, to='myapp.tiposimb'),
        ),
        migrations.AlterField(
            model_name='colonias',
            name='colonia_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
