# Generated by Django 4.2.7 on 2024-01-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_comentarios_options_alter_honorarios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='avaluo_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='avaluo_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='honorario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='razon',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
