# Generated by Django 4.2.7 on 2023-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_avaluos_avaluoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='clienteid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colonias',
            name='colonia_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estados',
            name='estado_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='estatusid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='municipio_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='tipoid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valuadores',
            name='valuadorid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
