# Generated by Django 4.2.7 on 2023-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_clientes_clienteid_alter_colonias_colonia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluos',
            name='calle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='consecutivo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtcliente',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtcobro',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtcreate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtpago',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtsolicitud',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='dtvaluador',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='entrecalle1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='entrecalle2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='m2c',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='m2t',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='manzana',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='monto',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='nofactura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='nofolio',
            field=models.ImageField(blank=True, max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numero_dictamen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='numeroint',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='tipoimbid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='avaluos',
            name='valor',
            field=models.FloatField(blank=True),
        ),
    ]
